language: generic
services:
  - docker

before_install:
  - docker build -t sandersmoen/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sandersmoen/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-299169563989'
  bucket_path: 'docker-react'
  on:
    branch: master
  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
