language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sandersmoen/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sandersmoen/docker-react npm run test -- --coverage
